-   id: commitlint
    name: Commit message linter (commitlint)
    entry: commitlint --edit
    language: node
    always_run: true
    additional_dependencies: ['commitlint']
-   id: commitizen
    name: Ensure commitizen is used for commit messages
    entry: exec < /dev/tty && node_modules/.bin/git-cz --hook || true
    language: system
    always_run: true